name: Run main.py every hour

on:
  schedule:
    - cron: "0 12 * * *" # Codziennie o 12:00
  workflow_dispatch: # Ręczne uruchomienie

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        shell: bash
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: python projekt.py "$CONFIG"